openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-redis
components:
  schemas:
    variables:
      required: []
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              namespace: string, optional
              image_registry: string, optional
              domain_suffix: string, optional
            ```
          default: {}
          properties:
            domain_suffix:
              default: cluster.local
              title: Domain Suffix
              type: string
            image_registry:
              default: registry-1.docker.io
              title: Image Registry
              type: string
            namespace:
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/redis/tags.
          default: "7.0"
          x-walrus-ui:
            group: Basic
            order: 5
        password:
          title: Password
          type: string
          description: |
            Specify the account password.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 6
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.

            Examples:
            ```
            resources:
              cpu: number, optional
              memory: number, optioanl       # in megabyte
            ```
          default:
            cpu: 0.25
            memory: 256
          required:
          - cpu
          - memory
          properties:
            cpu:
              title: Cpu
              type: number
            memory:
              title: Memory
              type: number
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.

            Examples:
            ```
            storage:                         # convert to empty_dir volume or dynamic volume claim template
              class: string, optional
              size: number, optional         # in megabyte
            ```
          properties:
            class:
              title: Class
              type: string
            size:
              default: 20480
              title: Size
              type: number
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
